### ISSUE TITLE
Oblivious integer type

### ISSUE THREAD

**Issue by Drup** [lukstafi/invargent#1]
Sometime I want an integer that is really just an integer but invargent tries to track the operations if I use Num. Example:

``` ocaml
datatype List : type * num
datacons LNil : ∀a. List(a, 0)
datacons LCons : ∀n, a. a * List(a, n) ⟶ List(a, n+1)

datatype Term : num
datacons Add : all n, m. Term n * Term m --> Term (n+m)
datacons Var : Term 1
datacons Val : all n. Num n --> Term 0

let rec eval = function
  | l, Val i -> (l,i)
  | LCons (x,xs), Var -> (xs, x)
  | l,Add(t1, t2) ->
    let (l', i1) = eval (l, t1) in
    let (l'', i2) = eval (l', t2) in
    (l'', i1 + i2)
```

fails with `No answer in num: numerical abduction failed` but if I use an abstract type:

``` ocaml
datatype List : type * num
datacons LNil : ∀a. List(a, 0)
datacons LCons : ∀n, a. a * List(a, n) ⟶ List(a, n+1)

datatype Term : num
datacons Add : all n, m. Term n * Term m --> Term (n+m)
datacons Var : Term 1
datacons Val : Float --> Term 0

external plusF : Float -> Float -> Float
let rec eval = function
  | l, Val i -> (l,i)
  | LCons (x,xs), Var -> (xs, x)
  | l,Add(t1, t2) ->
    let (l', i1) = eval (l, t1) in
    let (l'', i2) = eval (l', t2) in
    (l'', plusF i1 i2)
```

it works and gives me the expected type signature: `∀k, n. (List (Float, n + k), Term k) → (List (Float, n), Float)` (yay !)

Side note: the parser choke on (+.) in the external declaration.

**Comment by lukstafi** [comment]
Thanks for checking out InvarGenT!

On Mon, Apr 6, 2015 at 4:40 PM, Gabriel Radanne notifications@github.com
wrote:

> Sometime I want an integer that is really just an integer but invargent
> tries to track the operations if I use Num.
> 
> Then you should use the built-in type `Int`. Unfortunately, number literals
> (e.g. 0, 1, 2, etc.) will still be parsed as `Num`.
> 
> Side note: the parser choke on (+.) in the external declaration.
> 
> At this point, InvarGenT is still an academic project. It has a simple
> lexer and rather simple parser. In examples I use "external let" for these
> cases.

Have a nice evening!

**Comment by Drup** [comment]
> Then you should use the built-in type "Int". Unfortunately, number literals (e.g. 0, 1, 2, etc.) will still be parsed as "Num".

I tried that, but for whatever reason, it failed. How are you supposed to enter Int literals ?

**Comment by Drup** [comment]
Oh, I probably used +, is it only for Num too ?

**Comment by lukstafi** [comment]
Yes. In fact, `+` is hard-coded for `Num`, there are no user-defined or generic infix operators. You can define Int literals as any other values:

```
external let i0 : Int = "0"
external let i1 : Int = "1"
external let i2 : Int = "2"
```

Sorry for the burden to be that explicit.

**Comment by lukstafi** [comment]
What's worse, there's an outstanding parser bug for some uses of `-` I forgot to fix...
