### ISSUE TITLE
Use a syntax closer to OCaml's gadt

### ISSUE THREAD

**Issue by Drup** [lukstafi/invargent#3]
Pretty much the title. While I appreciate the slightly more adapted syntax, I would prefer tooling compatibility (ocp-indent in particular become really crazy with "datatype").

For kinds, we could reuse `:` in type expression:

``` ocaml
type (_:type, _:num) list =
  | LNil : 'a. ('a, 0) list
  | LCons : 'n 'a. 'a * ('a, 'n) list -> ('a, 'n + 1) list
```

**Comment by lukstafi** [comment]
I had developed the syntax used in InvarGenT for its predecessor, long before GADTs were added to OCaml... I could have decided to use OCaml's syntax, but instead I started with the parser from the older project. Changing the syntax is a reasonable suggestion.

**Comment by lukstafi** [comment]
I am not sure about changing the syntax all the way to OCaml's syntax. Would it suffice for you if there was an alternative syntax for `datatype` and `datacons` , but types still started with a capital letter and type variables without the `'`?

**Comment by Drup** [comment]
I think it would be already better wrt to the tooling, yes.

**Comment by lukstafi** [comment]
Alternative syntax for `datatype` and `datacons` items, using the `type` keyword instead, in most recent commit.
