### ISSUE TITLE
Do not erase files by default

### ISSUE THREAD

**Issue by Drup** [lukstafi/invargent#4]
A -f to force erasure of the various generated file and a -o option to precise where to output would be very useful and less error-prone.

**Comment by lukstafi** [comment]
Thanks, will do.

**Comment by lukstafi** [comment]
Should the `.gadti` files always be overwritten?

**Comment by Drup** [comment]
Well, writing one yourself is pointless at the moment, isn't it ? So I guess, yes.

**Comment by Drup** [comment]
I think they should just not be generated all the time, and only when an argument is provided, though.

**Comment by lukstafi** [comment]
Guarding against existing `.ml` files and alternative names for them in the most recent commit.
