### ISSUE TITLE
append (and flatten) List typing

### ISSUE THREAD

**Issue by Drup** [lukstafi/invargent#5]
When I used the list type commonly defined in your examples: 

```
datatype List : type * num
datacons LNil : ∀a. List(a, 0)
datacons LCons : ∀n, a [0≤n]. a * List(a, n) ⟶ List(a, n+1)
```

The append function

```
let rec append l1 l2 = match l1 with
  | LNil -> l2
  | LCons (h,t) -> LCons (h,append t l2)
```

get type 

```
∀k, n, a[1 ≤ k + n ∧ 1 ≤ n].
  List (a, k) → List (a, n) → List (a, n + k)
```

however, I don't see why the second list should have a length of at least one.
I can "fix" it by removing the constraint in LCons: `datacons LCons : ∀n, a. a * List(a, n) ⟶ List(a, n+1)`.

If I define flatten:

```
let rec flatten = function
  | LNil -> LNil
  | LCons (t, l) -> append t (flatten l)
```

The original version get a timeout. The modified version get the rather uninteresting `∀n, a. List (List (a, 0), n) → List (a, 0)`.

**Comment by lukstafi** [comment]
The problem with `append` is a known issue discussed in the documentation. See [GADTs for Reconstruction of Invariants and Postconditions](http://www.ii.uni.wroc.pl/~lukstafi/pmwiki/uploads/Infer/lukstafi-phd-thesis.pdf) Subsection 5.2.2.

The case of `flatten` is that it does not have a type (ETA: in current InvarGenT) without the use of existential types. The length of the resulting list is ~~not known~~ ETA: "k \* n" i.e. not expressible. Use:

```
let rec flatten = efunction
  | LNil -> LNil
  | LCons (t, l) ->
    let l' = flatten l in
    append t l'
```

Then, I get:

```
val append :
  ∀k, n, a[0 ≤ n]. List (a, k) → List (a, n) → List (a, n + k)
val flatten :
  ∀k, n, a[0 ≤ n]. List (List (a, n), k) → ∃n[0 ≤ n].List (a, n)
```

**Comment by Drup** [comment]
> `val flatten : ∀k, n, a[0 ≤ n]. List (List (a, n), k) → ∃n[0 ≤ n].List (a, n)`

invargent can't infer k \* n ?

**Comment by lukstafi** [comment]
You are right, I haven't noticed that indeed "k \* n" is the correct type
here! InvarGenT can't infer "k \* n" because its logic only allows linear
combinations, i.e. multiplying a variable by a constant and adding things.

**Comment by lukstafi** [comment]
It might be possible in the future. There has been work done on constraint generalization for polynomials, but I'm not aware of work on constraint abduction for polynomials. However, integration of it all into a single domain of numbers would be hard.
